export const ocene = [
  {
    rating: 3,
    comment: "Would not recommend!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Eleanor Collins",
    reviewerEmail: "eleanor.collins@x.dummyjson.com",
    productId: 1,
  },
  {
    rating: 4,
    comment: "Very satisfied!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Lucas Gordon",
    reviewerEmail: "lucas.gordon@x.dummyjson.com",
    productId: 1,
  },
  {
    rating: 5,
    comment: "Highly impressed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Eleanor Collins",
    reviewerEmail: "eleanor.collins@x.dummyjson.com",
    productId: 1,
  },
  {
    rating: 5,
    comment: "Great product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Savannah Gomez",
    reviewerEmail: "savannah.gomez@x.dummyjson.com",
    productId: 2,
  },
  {
    rating: 4,
    comment: "Awesome product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Christian Perez",
    reviewerEmail: "christian.perez@x.dummyjson.com",
    productId: 2,
  },
  {
    rating: 1,
    comment: "Poor quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Nicholas Bailey",
    reviewerEmail: "nicholas.bailey@x.dummyjson.com",
    productId: 2,
  },
  {
    rating: 4,
    comment: "Would buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Alexander Jones",
    reviewerEmail: "alexander.jones@x.dummyjson.com",
    productId: 3,
  },
  {
    rating: 5,
    comment: "Highly impressed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Elijah Cruz",
    reviewerEmail: "elijah.cruz@x.dummyjson.com",
    productId: 3,
  },
  {
    rating: 1,
    comment: "Very dissatisfied!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Avery Perez",
    reviewerEmail: "avery.perez@x.dummyjson.com",
    productId: 3,
  },
  {
    rating: 4,
    comment: "Great product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Liam Garcia",
    reviewerEmail: "liam.garcia@x.dummyjson.com",
    productId: 4,
  },
  {
    rating: 5,
    comment: "Great product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Ruby Andrews",
    reviewerEmail: "ruby.andrews@x.dummyjson.com",
    productId: 4,
  },
  {
    rating: 5,
    comment: "Would buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Clara Berry",
    reviewerEmail: "clara.berry@x.dummyjson.com",
    productId: 4,
  },
  {
    rating: 2,
    comment: "Poor quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Benjamin Wilson",
    reviewerEmail: "benjamin.wilson@x.dummyjson.com",
    productId: 5,
  },
  {
    rating: 5,
    comment: "Great product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Liam Smith",
    reviewerEmail: "liam.smith@x.dummyjson.com",
    productId: 5,
  },
  {
    rating: 1,
    comment: "Very unhappy with my purchase!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Clara Berry",
    reviewerEmail: "clara.berry@x.dummyjson.com",
    productId: 5,
  },
  {
    rating: 2,
    comment: "Very disappointed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Layla Young",
    reviewerEmail: "layla.young@x.dummyjson.com",
    productId: 6,
  },
  {
    rating: 4,
    comment: "Fast shipping!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Daniel Cook",
    reviewerEmail: "daniel.cook@x.dummyjson.com",
    productId: 6,
  },
  {
    rating: 3,
    comment: "Not as described!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Jacob Cooper",
    reviewerEmail: "jacob.cooper@x.dummyjson.com",
    productId: 6,
  },
  {
    rating: 4,
    comment: "Highly impressed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Ruby Andrews",
    reviewerEmail: "ruby.andrews@x.dummyjson.com",
    productId: 7,
  },
  {
    rating: 5,
    comment: "Awesome product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Leah Henderson",
    reviewerEmail: "leah.henderson@x.dummyjson.com",
    productId: 7,
  },
  {
    rating: 5,
    comment: "Very happy with my purchase!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Xavier Wright",
    reviewerEmail: "xavier.wright@x.dummyjson.com",
    productId: 7,
  },
  {
    rating: 5,
    comment: "Great value for money!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Nicholas Bailey",
    reviewerEmail: "nicholas.bailey@x.dummyjson.com",
    productId: 8,
  },
  {
    rating: 4,
    comment: "Great value for money!",
    date: "2024-04-30T09:41:02.053Z",
    reviewerName: "Penelope Harper",
    reviewerEmail: "penelope.harper@x.dummyjson.com",
    productId: 8,
  },
  {
    rating: 4,
    comment: "Great product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Emma Miller",
    reviewerEmail: "emma.miller@x.dummyjson.com",
    productId: 8,
  },
  {
    rating: 4,
    comment: "Would buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Mateo Bennett",
    reviewerEmail: "mateo.bennett@x.dummyjson.com",
    productId: 9,
  },
  {
    rating: 4,
    comment: "Highly recommended!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Nolan Gonzalez",
    reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
    productId: 9,
  },
  {
    rating: 5,
    comment: "Very happy with my purchase!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Aurora Lawson",
    reviewerEmail: "aurora.lawson@x.dummyjson.com",
    productId: 9,
  },
  {
    rating: 1,
    comment: "Very dissatisfied!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Cameron Perez",
    reviewerEmail: "cameron.perez@x.dummyjson.com",
    productId: 10,
  },
  {
    rating: 5,
    comment: "Very happy with my purchase!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Daniel Cook",
    reviewerEmail: "daniel.cook@x.dummyjson.com",
    productId: 10,
  },
  {
    rating: 4,
    comment: "Highly impressed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Addison Wright",
    reviewerEmail: "addison.wright@x.dummyjson.com",
    productId: 10,
  },
  {
    rating: 2,
    comment: "Would not recommend!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Christopher West",
    reviewerEmail: "christopher.west@yahoo.com",
    productId: 11,
  },
  {
    rating: 4,
    comment: "Highly impressed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Vivian Carter",
    reviewerEmail: "vivian.carter@x.dummyjson.com",
    productId: 11,
  },
  {
    rating: 1,
    comment: "Poor quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Mason Wright",
    reviewerEmail: "mason.wright@x.dummyjson.com",
    productId: 11,
  },
  {
    rating: 3,
    comment: "Very unhappy with my purchase!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Christian Perez",
    reviewerEmail: "christian.perez@x.dummyjson.com",
    productId: 12,
  },
  {
    rating: 5,
    comment: "Fast shipping!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Lillian Bishop",
    reviewerEmail: "lillian.bishop@x.dummyjson.com",
    productId: 12,
  },
  {
    rating: 1,
    comment: "Poor quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Lillian Simmons",
    reviewerEmail: "lillian.simmons@x.dummyjson.com",
    productId: 12,
  },
  {
    rating: 4,
    comment: "Excellent quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Aaliyah Hanson",
    reviewerEmail: "aaliyah.hanson@x.dummyjson.com",
    productId: 13,
  },
  {
    rating: 4,
    comment: "Excellent quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Liam Smith",
    reviewerEmail: "liam.smith@x.dummyjson.com",
    productId: 13,
  },
  {
    rating: 4,
    comment: "Highly recommended!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Avery Barnes",
    reviewerEmail: "avery.barnes@x.dummyjson.com",
    productId: 13,
  },
  {
    rating: 2,
    comment: "Waste of money!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Ella Cook",
    reviewerEmail: "ella.cook@x.dummyjson.com",
    productId: 14,
  },
  {
    rating: 2,
    comment: "Very dissatisfied!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Clara Berry",
    reviewerEmail: "clara.berry@x.dummyjson.com",
    productId: 14,
  },
  {
    rating: 5,
    comment: "Would buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Elena Long",
    reviewerEmail: "elena.long@x.dummyjson.com",
    productId: 14,
  },
  {
    rating: 4,
    comment: "Fast shipping!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Logan Torres",
    reviewerEmail: "logan.torres@x.dummyjson.com",
    productId: 15,
  },
  {
    rating: 5,
    comment: "Very pleased!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Aria Parker",
    reviewerEmail: "aria.parker@x.dummyjson.com",
    productId: 15,
  },
  {
    rating: 3,
    comment: "Poor quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Dylan Wells",
    reviewerEmail: "dylan.wells@x.dummyjson.com",
    productId: 15,
  },
  {
    rating: 5,
    comment: "Very satisfied!",
    date: "2024-04-30T09:41:02.053Z",
    reviewerName: "Sophia Brown",
    reviewerEmail: "sophia.brown@x.dummyjson.com",
    productId: 16,
  },
  {
    rating: 1,
    comment: "Very dissatisfied!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Scarlett Bowman",
    reviewerEmail: "scarlett.bowman@x.dummyjson.com",
    productId: 16,
  },
  {
    rating: 3,
    comment: "Very unhappy with my purchase!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "William Gonzalez",
    reviewerEmail: "william.gonzalez@x.dummyjson.com",
    productId: 16,
  },
  {
    rating: 3,
    comment: "Would not recommend!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Eleanor Tyler",
    reviewerEmail: "eleanor.tyler@x.dummyjson.com",
    productId: 17,
  },
  {
    rating: 4,
    comment: "Fast shipping!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Alexander Jones",
    reviewerEmail: "alexander.jones@x.dummyjson.com",
    productId: 17,
  },
  {
    rating: 5,
    comment: "Great value for money!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Natalie Harris",
    reviewerEmail: "natalie.harris@x.dummyjson.com",
    productId: 17,
  },
  {
    rating: 3,
    comment: "Would not recommend!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Noah Lewis",
    reviewerEmail: "noah.lewis@x.dummyjson.com",
    productId: 18,
  },
  {
    rating: 3,
    comment: "Very unhappy with my purchase!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Ruby Andrews",
    reviewerEmail: "ruby.andrews@x.dummyjson.com",
    productId: 18,
  },
  {
    rating: 2,
    comment: "Very disappointed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Ethan Thompson",
    reviewerEmail: "ethan.thompson@x.dummyjson.com",
    productId: 18,
  },
  {
    rating: 5,
    comment: "Great product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Mateo Bennett",
    reviewerEmail: "mateo.bennett@x.dummyjson.com",
    productId: 19,
  },
  {
    rating: 4,
    comment: "Highly recommended!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Jackson Evans",
    reviewerEmail: "jackson.evans@x.dummyjson.com",
    productId: 19,
  },
  {
    rating: 3,
    comment: "Not worth the price!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Sadie Morales",
    reviewerEmail: "sadie.morales@x.dummyjson.com",
    productId: 19,
  },
  {
    rating: 5,
    comment: "Very happy with my purchase!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Victoria McDonald",
    reviewerEmail: "victoria.mcdonald@x.dummyjson.com",
    productId: 20,
  },
  {
    rating: 2,
    comment: "Would not recommend!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Hazel Evans",
    reviewerEmail: "hazel.evans@x.dummyjson.com",
    productId: 20,
  },
  {
    rating: 5,
    comment: "Would buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Zoe Bennett",
    reviewerEmail: "zoe.bennett@x.dummyjson.com",
    productId: 20,
  },
  {
    rating: 4,
    comment: "Great product!",
    date: "2024-04-30T09:41:02.053Z",
    reviewerName: "Lincoln Kelly",
    reviewerEmail: "lincoln.kelly@x.dummyjson.com",
    productId: 21,
  },
  {
    rating: 4,
    comment: "Great value for money!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Savannah Gomez",
    reviewerEmail: "savannah.gomez@x.dummyjson.com",
    productId: 21,
  },
  {
    rating: 2,
    comment: "Poor quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "James Davis",
    reviewerEmail: "james.davis@x.dummyjson.com",
    productId: 21,
  },
  {
    rating: 5,
    comment: "Excellent quality!",
    date: "2024-04-30T09:41:02.053Z",
    reviewerName: "Nicholas Edwards",
    reviewerEmail: "nicholas.edwards@x.dummyjson.com",
    productId: 22,
  },
  {
    rating: 5,
    comment: "Awesome product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Zachary Lee",
    reviewerEmail: "zachary.lee@x.dummyjson.com",
    productId: 22,
  },
  {
    rating: 4,
    comment: "Great product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Nova Cooper",
    reviewerEmail: "nova.cooper@x.dummyjson.com",
    productId: 22,
  },
  {
    rating: 3,
    comment: "Disappointing product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Penelope King",
    reviewerEmail: "penelope.king@x.dummyjson.com",
    productId: 23,
  },
  {
    rating: 3,
    comment: "Poor quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Eleanor Tyler",
    reviewerEmail: "eleanor.tyler@x.dummyjson.com",
    productId: 23,
  },
  {
    rating: 4,
    comment: "Very pleased!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Benjamin Foster",
    reviewerEmail: "benjamin.foster@yahoo.com",
    productId: 23,
  },
  {
    rating: 2,
    comment: "Would not buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Caleb Perkins",
    reviewerEmail: "caleb.perkins@x.dummyjson.com",
    productId: 24,
  },
  {
    rating: 5,
    comment: "Excellent quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Isabella Jackson",
    reviewerEmail: "isabella.jackson@x.dummyjson.com",
    productId: 24,
  },
  {
    rating: 4,
    comment: "Great value for money!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Nathan Dixon",
    reviewerEmail: "nathan.dixon@x.dummyjson.com",
    productId: 24,
  },
  {
    rating: 4,
    comment: "Highly recommended!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Avery Carter",
    reviewerEmail: "avery.carter@x.dummyjson.com",
    productId: 25,
  },
  {
    rating: 3,
    comment: "Would not recommend!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Henry Hill",
    reviewerEmail: "henry.hill@x.dummyjson.com",
    productId: 25,
  },
  {
    rating: 5,
    comment: "Excellent quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Addison Wright",
    reviewerEmail: "addison.wright@x.dummyjson.com",
    productId: 25,
  },
  {
    rating: 4,
    comment: "Great product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Luna Russell",
    reviewerEmail: "luna.russell@x.dummyjson.com",
    productId: 26,
  },
  {
    rating: 1,
    comment: "Waste of money!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Noah Lewis",
    reviewerEmail: "noah.lewis@x.dummyjson.com",
    productId: 26,
  },
  {
    rating: 3,
    comment: "Very disappointed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Clara Berry",
    reviewerEmail: "clara.berry@x.dummyjson.com",
    productId: 26,
  },
  {
    rating: 1,
    comment: "Very disappointed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Autumn Gomez",
    reviewerEmail: "autumn.gomez@x.dummyjson.com",
    productId: 27,
  },
  {
    rating: 4,
    comment: "Highly impressed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Benjamin Wilson",
    reviewerEmail: "benjamin.wilson@x.dummyjson.com",
    productId: 27,
  },
  {
    rating: 2,
    comment: "Very disappointed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Nicholas Edwards",
    reviewerEmail: "nicholas.edwards@x.dummyjson.com",
    productId: 27,
  },
  {
    rating: 5,
    comment: "Very pleased!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Elijah Cruz",
    reviewerEmail: "elijah.cruz@x.dummyjson.com",
    productId: 28,
  },
  {
    rating: 4,
    comment: "Excellent quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Jace Smith",
    reviewerEmail: "jace.smith@x.dummyjson.com",
    productId: 28,
  },
  {
    rating: 5,
    comment: "Highly impressed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Sadie Morales",
    reviewerEmail: "sadie.morales@x.dummyjson.com",
    productId: 28,
  },
  {
    rating: 5,
    comment: "Excellent quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Nolan Gonzalez",
    reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
    productId: 29,
  },
  {
    rating: 4,
    comment: "Would buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Bella Grant",
    reviewerEmail: "bella.grant@x.dummyjson.com",
    productId: 29,
  },
  {
    rating: 5,
    comment: "Awesome product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Aria Flores",
    reviewerEmail: "aria.flores@x.dummyjson.com",
    productId: 29,
  },
  {
    rating: 4,
    comment: "Highly recommended!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Emily Brown",
    reviewerEmail: "emily.brown@x.dummyjson.com",
    productId: 30,
  },
  {
    rating: 2,
    comment: "Would not buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Jackson Morales",
    reviewerEmail: "jackson.morales@x.dummyjson.com",
    productId: 30,
  },
  {
    rating: 4,
    comment: "Fast shipping!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Nora Russell",
    reviewerEmail: "nora.russell@x.dummyjson.com",
    productId: 30,
  },
  {
    rating: 5,
    comment: "Awesome product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Logan Lawson",
    reviewerEmail: "logan.lawson@yahoo.com",
    productId: 31,
  },
  {
    rating: 5,
    comment: "Highly impressed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Avery Perez",
    reviewerEmail: "avery.perez@x.dummyjson.com",
    productId: 31,
  },
  {
    rating: 5,
    comment: "Very satisfied!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Benjamin Foster",
    reviewerEmail: "benjamin.foster@x.dummyjson.com",
    productId: 31,
  },
  {
    rating: 4,
    comment: "Very satisfied!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Nicholas Bailey",
    reviewerEmail: "nicholas.bailey@x.dummyjson.com",
    productId: 32,
  },
  {
    rating: 3,
    comment: "Would not buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Harper Turner",
    reviewerEmail: "harper.turner@x.dummyjson.com",
    productId: 32,
  },
  {
    rating: 5,
    comment: "Great value for money!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Autumn Gomez",
    reviewerEmail: "autumn.gomez@x.dummyjson.com",
    productId: 32,
  },
  {
    rating: 5,
    comment: "Fast shipping!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Avery Barnes",
    reviewerEmail: "avery.barnes@x.dummyjson.com",
    productId: 33,
  },
  {
    rating: 2,
    comment: "Not worth the price!",
    date: "2024-04-30T09:41:02.053Z",
    reviewerName: "Sadie Morales",
    reviewerEmail: "sadie.morales@x.dummyjson.com",
    productId: 33,
  },
  {
    rating: 1,
    comment: "Would not buy again!",
    date: "2024-04-30T09:41:02.053Z",
    reviewerName: "Oscar Powers",
    reviewerEmail: "oscar.powers@x.dummyjson.com",
    productId: 33,
  },
  {
    rating: 5,
    comment: "Very pleased!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Gabriel Adams",
    reviewerEmail: "gabriel.adams@x.dummyjson.com",
    productId: 34,
  },
  {
    rating: 5,
    comment: "Highly recommended!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Ella Cook",
    reviewerEmail: "ella.cook@x.dummyjson.com",
    productId: 34,
  },
  {
    rating: 4,
    comment: "Would buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Logan Torres",
    reviewerEmail: "logan.torres@x.dummyjson.com",
    productId: 34,
  },
  {
    rating: 5,
    comment: "Highly impressed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Eleanor Collins",
    reviewerEmail: "eleanor.collins@x.dummyjson.com",
    productId: 35,
  },
  {
    rating: 4,
    comment: "Fast shipping!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Lily Torres",
    reviewerEmail: "lily.torres@x.dummyjson.com",
    productId: 35,
  },
  {
    rating: 5,
    comment: "Highly recommended!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Ariana Ross",
    reviewerEmail: "ariana.ross@x.dummyjson.com",
    productId: 35,
  },
  {
    rating: 3,
    comment: "Very unhappy with my purchase!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Aurora Rodriguez",
    reviewerEmail: "aurora.rodriguez@x.dummyjson.com",
    productId: 36,
  },
  {
    rating: 4,
    comment: "Would buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Miles Stevenson",
    reviewerEmail: "miles.stevenson@x.dummyjson.com",
    productId: 36,
  },
  {
    rating: 4,
    comment: "Very happy with my purchase!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Clara Berry",
    reviewerEmail: "clara.berry@x.dummyjson.com",
    productId: 36,
  },
  {
    rating: 4,
    comment: "Fast shipping!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Maya Reed",
    reviewerEmail: "maya.reed@x.dummyjson.com",
    productId: 37,
  },
  {
    rating: 3,
    comment: "Very dissatisfied!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Evelyn Gonzalez",
    reviewerEmail: "evelyn.gonzalez@x.dummyjson.com",
    productId: 37,
  },
  {
    rating: 5,
    comment: "Awesome product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Jackson Evans",
    reviewerEmail: "jackson.evans@x.dummyjson.com",
    productId: 37,
  },
  {
    rating: 5,
    comment: "Would buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Sophia Brown",
    reviewerEmail: "sophia.brown@x.dummyjson.com",
    productId: 38,
  },
  {
    rating: 4,
    comment: "Very satisfied!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Grace Perry",
    reviewerEmail: "grace.perry@x.dummyjson.com",
    productId: 38,
  },
  {
    rating: 1,
    comment: "Very disappointed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Cameron Burke",
    reviewerEmail: "cameron.burke@x.dummyjson.com",
    productId: 38,
  },
  {
    rating: 2,
    comment: "Would not recommend!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Zachary Lee",
    reviewerEmail: "zachary.lee@x.dummyjson.com",
    productId: 39,
  },
  {
    rating: 2,
    comment: "Would not recommend!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Oscar Powers",
    reviewerEmail: "oscar.powers@x.dummyjson.com",
    productId: 39,
  },
  {
    rating: 5,
    comment: "Highly recommended!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Hannah Robinson",
    reviewerEmail: "hannah.robinson@x.dummyjson.com",
    productId: 39,
  },
  {
    rating: 3,
    comment: "Would not buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Amelia Perez",
    reviewerEmail: "amelia.perez@x.dummyjson.com",
    productId: 40,
  },
  {
    rating: 3,
    comment: "Would not buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Olivia Wilson",
    reviewerEmail: "olivia.wilson@x.dummyjson.com",
    productId: 40,
  },
  {
    rating: 4,
    comment: "Would buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Hunter Gordon",
    reviewerEmail: "hunter.gordon@x.dummyjson.com",
    productId: 40,
  },
  {
    rating: 1,
    comment: "Not as described!",
    date: "2024-04-30T09:41:02.053Z",
    reviewerName: "Ariana Ross",
    reviewerEmail: "ariana.ross@x.dummyjson.com",
    productId: 41,
  },
  {
    rating: 5,
    comment: "Fast shipping!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Carter Baker",
    reviewerEmail: "carter.baker@x.dummyjson.com",
    productId: 41,
  },
  {
    rating: 5,
    comment: "Great value for money!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Penelope Harper",
    reviewerEmail: "penelope.harper@x.dummyjson.com",
    productId: 41,
  },
  {
    rating: 5,
    comment: "Highly impressed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Jonathan Pierce",
    reviewerEmail: "jonathan.pierce@x.dummyjson.com",
    productId: 42,
  },
  {
    rating: 2,
    comment: "Would not recommend!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Grayson Coleman",
    reviewerEmail: "grayson.coleman@x.dummyjson.com",
    productId: 42,
  },
  {
    rating: 3,
    comment: "Not as described!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Ethan Fletcher",
    reviewerEmail: "ethan.fletcher@x.dummyjson.com",
    productId: 42,
  },
  {
    rating: 1,
    comment: "Would not buy again!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Daniel Cook",
    reviewerEmail: "daniel.cook@x.dummyjson.com",
    productId: 43,
  },
  {
    rating: 2,
    comment: "Poor quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Hunter Gordon",
    reviewerEmail: "hunter.gordon@x.dummyjson.com",
    productId: 43,
  },
  {
    rating: 3,
    comment: "Very unhappy with my purchase!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Stella Morris",
    reviewerEmail: "stella.morris@yahoo.com",
    productId: 43,
  },
  {
    rating: 4,
    comment: "Highly impressed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Oscar Powers",
    reviewerEmail: "oscar.powers@x.dummyjson.com",
    productId: 44,
  },
  {
    rating: 5,
    comment: "Excellent quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Austin Hudson",
    reviewerEmail: "austin.hudson@x.dummyjson.com",
    productId: 44,
  },
  {
    rating: 2,
    comment: "Very dissatisfied!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Luke Cooper",
    reviewerEmail: "luke.cooper@x.dummyjson.com",
    productId: 44,
  },
  {
    rating: 5,
    comment: "Very happy with my purchase!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Natalie Harris",
    reviewerEmail: "natalie.harris@x.dummyjson.com",
    productId: 45,
  },
  {
    rating: 1,
    comment: "Poor quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Max Russell",
    reviewerEmail: "max.russell@x.dummyjson.com",
    productId: 45,
  },
  {
    rating: 5,
    comment: "Very pleased!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Nolan Gonzalez",
    reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
    productId: 45,
  },
  {
    rating: 4,
    comment: "Fast shipping!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Vivian Carter",
    reviewerEmail: "vivian.carter@x.dummyjson.com",
    productId: 46,
  },
  {
    rating: 5,
    comment: "Very satisfied!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Ella Adams",
    reviewerEmail: "ella.adams@x.dummyjson.com",
    productId: 46,
  },
  {
    rating: 3,
    comment: "Poor quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Liam Smith",
    reviewerEmail: "liam.smith@x.dummyjson.com",
    productId: 46,
  },
  {
    rating: 5,
    comment: "Excellent quality!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Benjamin Foster",
    reviewerEmail: "benjamin.foster@x.dummyjson.com",
    productId: 47,
  },
  {
    rating: 3,
    comment: "Would not recommend!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Sophia Jones",
    reviewerEmail: "sophia.jones@x.dummyjson.com",
    productId: 47,
  },
  {
    rating: 5,
    comment: "Awesome product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Natalie Harris",
    reviewerEmail: "natalie.harris@x.dummyjson.com",
    productId: 47,
  },
  {
    rating: 5,
    comment: "Awesome product!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Lucas Ramirez",
    reviewerEmail: "lucas.ramirez@x.dummyjson.com",
    productId: 48,
  },
  {
    rating: 5,
    comment: "Highly recommended!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Caleb Perkins",
    reviewerEmail: "caleb.perkins@x.dummyjson.com",
    productId: 48,
  },
  {
    rating: 4,
    comment: "Highly recommended!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Nolan Gonzalez",
    reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
    productId: 48,
  },
  {
    rating: 3,
    comment: "Very disappointed!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Alexander Hernandez",
    reviewerEmail: "alexander.hernandez@x.dummyjson.com",
    productId: 49,
  },
  {
    rating: 5,
    comment: "Great value for money!",
    date: "2024-04-30T09:41:02.053Z",
    reviewerName: "Aurora Rodriguez",
    reviewerEmail: "aurora.rodriguez@x.dummyjson.com",
    productId: 49,
  },
  {
    rating: 1,
    comment: "Not worth the price!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Benjamin Foster",
    reviewerEmail: "benjamin.foster@x.dummyjson.com",
    productId: 49,
  },
  {
    rating: 3,
    comment: "Not worth the price!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Cameron Perez",
    reviewerEmail: "cameron.perez@x.dummyjson.com",
    productId: 50,
  },
  {
    rating: 1,
    comment: "Waste of money!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Benjamin Foster",
    reviewerEmail: "benjamin.foster@x.dummyjson.com",
    productId: 50,
  },
  {
    rating: 5,
    comment: "Very pleased!",
    date: "2025-04-30T09:41:02.053Z",
    reviewerName: "Paisley Bell",
    reviewerEmail: "paisley.bell@x.dummyjson.com",
    productId: 50,
  },
];
