export const proizvodi = [
  {
    id: 1,
    title: "Essence Mascara Lash Princess",
    category: "beauty",
    price: 9.99,
    stock: 99,
  },
  {
    id: 2,
    title: "Eyeshadow Palette with Mirror",
    category: "beauty",
    price: 19.99,
    stock: 34,
  },
  {
    id: 3,
    title: "Powder Canister",
    category: "beauty",
    price: 14.99,
    stock: 89,
  },
  {
    id: 4,
    title: "Red Lipstick",
    category: "beauty",
    price: 12.99,
    stock: 91,
  },
  {
    id: 5,
    title: "Red Nail Polish",
    category: "beauty",
    price: 8.99,
    stock: 79,
  },
  {
    id: 6,
    title: "Calvin Klein CK One",
    category: "fragrances",
    price: 49.99,
    stock: 29,
  },
  {
    id: 7,
    title: "Chanel Coco Noir Eau De",
    category: "fragrances",
    price: 129.99,
    stock: 58,
  },
  {
    id: 8,
    title: "Dior J'adore",
    category: "fragrances",
    price: 89.99,
    stock: 98,
  },
  {
    id: 9,
    title: "Dolce Shine Eau de",
    category: "fragrances",
    price: 69.99,
    stock: 4,
  },
  {
    id: 10,
    title: "Gucci Bloom Eau de",
    category: "fragrances",
    price: 79.99,
    stock: 91,
  },
  {
    id: 11,
    title: "Annibale Colombo Bed",
    category: "furniture",
    price: 1899.99,
    stock: 88,
  },
  {
    id: 12,
    title: "Annibale Colombo Sofa",
    category: "furniture",
    price: 2499.99,
    stock: 60,
  },
  {
    id: 13,
    title: "Bedside Table African Cherry",
    category: "furniture",
    price: 299.99,
    stock: 64,
  },
  {
    id: 14,
    title: "Knoll Saarinen Executive Conference Chair",
    category: "furniture",
    price: 499.99,
    stock: 26,
  },
  {
    id: 15,
    title: "Wooden Bathroom Sink With Mirror",
    category: "furniture",
    price: 799.99,
    stock: 7,
  },
  {
    id: 16,
    title: "Apple",
    category: "groceries",
    price: 1.99,
    stock: 8,
  },
  {
    id: 17,
    title: "Beef Steak",
    category: "groceries",
    price: 12.99,
    stock: 86,
  },
  {
    id: 18,
    title: "Cat Food",
    category: "groceries",
    price: 8.99,
    stock: 46,
  },
  {
    id: 19,
    title: "Chicken Meat",
    category: "groceries",
    price: 9.99,
    stock: 97,
  },
  {
    id: 20,
    title: "Cooking Oil",
    category: "groceries",
    price: 4.99,
    stock: 10,
  },
  {
    id: 21,
    title: "Cucumber",
    category: "groceries",
    price: 1.49,
    stock: 84,
  },
  {
    id: 22,
    title: "Dog Food",
    category: "groceries",
    price: 10.99,
    stock: 71,
  },
  {
    id: 23,
    title: "Eggs",
    category: "groceries",
    price: 2.99,
    stock: 9,
  },
  {
    id: 24,
    title: "Fish Steak",
    category: "groceries",
    price: 14.99,
    stock: 74,
  },
  {
    id: 25,
    title: "Green Bell Pepper",
    category: "groceries",
    price: 1.29,
    stock: 33,
  },
  {
    id: 26,
    title: "Green Chili Pepper",
    category: "groceries",
    price: 0.99,
    stock: 3,
  },
  {
    id: 27,
    title: "Honey Jar",
    category: "groceries",
    price: 6.99,
    stock: 34,
  },
  {
    id: 28,
    title: "Ice Cream",
    category: "groceries",
    price: 5.49,
    stock: 27,
  },
  {
    id: 29,
    title: "Juice",
    category: "groceries",
    price: 3.99,
    stock: 50,
  },
  {
    id: 30,
    title: "Kiwi",
    category: "groceries",
    price: 2.49,
    stock: 99,
  },
  {
    id: 31,
    title: "Lemon",
    category: "groceries",
    price: 0.79,
    stock: 31,
  },
  {
    id: 32,
    title: "Milk",
    category: "groceries",
    price: 3.49,
    stock: 27,
  },
  {
    id: 33,
    title: "Mulberry",
    category: "groceries",
    price: 4.99,
    stock: 99,
  },
  {
    id: 34,
    title: "Nescafe Coffee",
    category: "groceries",
    price: 7.99,
    stock: 57,
  },
  {
    id: 35,
    title: "Potatoes",
    category: "groceries",
    price: 2.29,
    stock: 13,
  },
  {
    id: 36,
    title: "Protein Powder",
    category: "groceries",
    price: 19.99,
    stock: 80,
  },
  {
    id: 37,
    title: "Red Onions",
    category: "groceries",
    price: 1.99,
    stock: 82,
  },
  {
    id: 38,
    title: "Rice",
    category: "groceries",
    price: 5.99,
    stock: 59,
  },
  {
    id: 39,
    title: "Soft Drinks",
    category: "groceries",
    price: 1.99,
    stock: 53,
  },
  {
    id: 40,
    title: "Strawberry",
    category: "groceries",
    price: 3.99,
    stock: 46,
  },
  {
    id: 41,
    title: "Tissue Paper Box",
    category: "groceries",
    price: 2.49,
    stock: 86,
  },
  {
    id: 42,
    title: "Water",
    category: "groceries",
    price: 0.99,
    stock: 53,
  },
  {
    id: 43,
    title: "Decoration Swing",
    category: "home-decoration",
    price: 59.99,
    stock: 47,
  },
  {
    id: 44,
    title: "Family Tree Photo Frame",
    category: "home-decoration",
    price: 29.99,
    stock: 77,
  },
  {
    id: 45,
    title: "House Showpiece Plant",
    category: "home-decoration",
    price: 39.99,
    stock: 28,
  },
  {
    id: 46,
    title: "Plant Pot",
    category: "home-decoration",
    price: 14.99,
    stock: 59,
  },
  {
    id: 47,
    title: "Table Lamp",
    category: "home-decoration",
    price: 49.99,
    stock: 9,
  },
  {
    id: 48,
    title: "Bamboo Spatula",
    category: "kitchen-accessories",
    price: 7.99,
    stock: 37,
  },
  {
    id: 49,
    title: "Black Aluminium Cup",
    category: "kitchen-accessories",
    price: 5.99,
    stock: 75,
  },
  {
    id: 50,
    title: "Black Whisk",
    category: "kitchen-accessories",
    price: 9.99,
    stock: 73,
  },
];
