export const songData = [
  {
    id: "1",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    tags: "rock,classic,70s",
  },
  {
    id: "2",
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    tags: "grunge,90s,alternative",
  },
  {
    id: "3",
    title: "Billie Jean",
    artist: "Michael Jackson",
    tags: "pop,80s,dance",
  },
  {
    id: "4",
    title: "Imagine",
    artist: "John Lennon",
    tags: "rock,piano,peace",
  },
  {
    id: "5",
    title: "Hotel California",
    artist: "Eagles",
    tags: "rock,classic,70s",
  },
  {
    id: "6",
    title: "Like a Rolling Stone",
    artist: "Bob Dylan",
    tags: "folk,rock,60s",
  },
  {
    id: "7",
    title: "Hey Jude",
    artist: "The Beatles",
    tags: "rock,classic,60s",
  },
  {
    id: "8",
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    tags: "rock,classic,guitar",
  },
  { id: "9", title: "Purple Rain", artist: "Prince", tags: "pop,rock,80s" },
  { id: "10", title: "Wonderwall", artist: "Oasis", tags: "rock,90s,britpop" },
  {
    id: "11",
    title: "Shape of You",
    artist: "Ed Sheeran",
    tags: "pop,2010s,acoustic",
  },
  {
    id: "12",
    title: "Lose Yourself",
    artist: "Eminem",
    tags: "hip-hop,2000s,rap",
  },
  { id: "13", title: "All Star", artist: "Smash Mouth", tags: "pop,rock,90s" },
  {
    id: "14",
    title: "Rolling in the Deep",
    artist: "Adele",
    tags: "pop,soul,2010s",
  },
  {
    id: "15",
    title: "Hallelujah",
    artist: "Leonard Cohen",
    tags: "folk,classic,ballad",
  },
  {
    id: "16",
    title: "Creep",
    artist: "Radiohead",
    tags: "rock,alternative,90s",
  },
  {
    id: "17",
    title: "Poker Face",
    artist: "Lady Gaga",
    tags: "pop,dance,2000s",
  },
  {
    id: "18",
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    tags: "rock,80s,guitar",
  },
  {
    id: "19",
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    tags: "funk,pop,2010s",
  },
  {
    id: "20",
    title: "Mr. Brightside",
    artist: "The Killers",
    tags: "rock,2000s,indie",
  },
  {
    id: "21",
    title: "Shake It Off",
    artist: "Taylor Swift",
    tags: "pop,2010s,dance",
  },
  {
    id: "22",
    title: "Radioactive",
    artist: "Imagine Dragons",
    tags: "rock,alternative,2010s",
  },
  {
    id: "23",
    title: "Seven Nation Army",
    artist: "The White Stripes",
    tags: "rock,2000s,garage",
  },
  {
    id: "24",
    title: "Thunderstruck",
    artist: "AC/DC",
    tags: "rock,classic,80s",
  },
  { id: "25", title: "Take On Me", artist: "a-ha", tags: "pop,80s,synth" },
  {
    id: "26",
    title: "Call Me Maybe",
    artist: "Carly Rae Jepsen",
    tags: "pop,2010s,dance",
  },
  {
    id: "27",
    title: "Numb",
    artist: "Linkin Park",
    tags: "rock,2000s,nu-metal",
  },
  { id: "28", title: "Clocks", artist: "Coldplay", tags: "rock,pop,2000s" },
  {
    id: "29",
    title: "Old Town Road",
    artist: "Lil Nas X",
    tags: "rap,country,2010s",
  },
  { id: "30", title: "Africa", artist: "Toto", tags: "rock,80s,pop" },
];
