export const zaposleni = [
  {
    id: 1,
    firstName: "Emily",
    lastName: "Johnson",
    gender: "female",
    age: 28,
    email: "emily.johnson@x.dummyjson.com",
    role: "admin",
  },
  {
    id: 2,
    firstName: "Michael",
    lastName: "Williams",
    gender: "male",
    age: 35,
    email: "michael.williams@x.dummyjson.com",
    role: "admin",
  },
  {
    id: 3,
    firstName: "Sophia",
    lastName: "Brown",
    gender: "female",
    age: 42,
    email: "sophia.brown@x.dummyjson.com",
    role: "admin",
  },
  {
    id: 4,
    firstName: "James",
    lastName: "Davis",
    gender: "male",
    age: 45,
    email: "james.davis@x.dummyjson.com",
    role: "admin",
  },
  {
    id: 5,
    firstName: "Emma",
    lastName: "Miller",
    gender: "female",
    age: 30,
    email: "emma.miller@x.dummyjson.com",
    role: "admin",
  },
  {
    id: 6,
    firstName: "Olivia",
    lastName: "Wilson",
    gender: "female",
    age: 22,
    email: "olivia.wilson@x.dummyjson.com",
    role: "moderator",
  },
  {
    id: 7,
    firstName: "Alexander",
    lastName: "Jones",
    gender: "male",
    age: 38,
    email: "alexander.jones@x.dummyjson.com",
    role: "moderator",
  },
  {
    id: 8,
    firstName: "Ava",
    lastName: "Taylor",
    gender: "female",
    age: 27,
    email: "ava.taylor@x.dummyjson.com",
    role: "moderator",
  },
  {
    id: 9,
    firstName: "Ethan",
    lastName: "Martinez",
    gender: "male",
    age: 33,
    email: "ethan.martinez@x.dummyjson.com",
    role: "moderator",
  },
  {
    id: 10,
    firstName: "Isabella",
    lastName: "Anderson",
    gender: "female",
    age: 31,
    email: "isabella.anderson@x.dummyjson.com",
    role: "moderator",
  },
  {
    id: 11,
    firstName: "Liam",
    lastName: "Garcia",
    gender: "male",
    age: 29,
    email: "liam.garcia@x.dummyjson.com",
    role: "moderator",
  },
  {
    id: 12,
    firstName: "Mia",
    lastName: "Rodriguez",
    gender: "female",
    age: 24,
    email: "mia.rodriguez@x.dummyjson.com",
    role: "moderator",
  },
  {
    id: 13,
    firstName: "Noah",
    lastName: "Hernandez",
    gender: "male",
    age: 40,
    email: "noah.hernandez@x.dummyjson.com",
    role: "moderator",
  },
  {
    id: 14,
    firstName: "Charlotte",
    lastName: "Lopez",
    gender: "female",
    age: 36,
    email: "charlotte.lopez@x.dummyjson.com",
    role: "moderator",
  },
  {
    id: 15,
    firstName: "William",
    lastName: "Gonzalez",
    gender: "male",
    age: 32,
    email: "william.gonzalez@x.dummyjson.com",
    role: "moderator",
  },
  {
    id: 16,
    firstName: "Avery",
    lastName: "Perez",
    gender: "female",
    age: 25,
    email: "avery.perez@x.dummyjson.com",
    role: "user",
  },
  {
    id: 17,
    firstName: "Evelyn",
    lastName: "Sanchez",
    gender: "female",
    age: 37,
    email: "evelyn.sanchez@x.dummyjson.com",
    role: "user",
  },
  {
    id: 18,
    firstName: "Logan",
    lastName: "Torres",
    gender: "male",
    age: 31,
    email: "logan.torres@x.dummyjson.com",
    role: "user",
  },
  {
    id: 19,
    firstName: "Abigail",
    lastName: "Rivera",
    gender: "female",
    age: 28,
    email: "abigail.rivera@x.dummyjson.com",
    role: "user",
  },
  {
    id: 20,
    firstName: "Jackson",
    lastName: "Evans",
    gender: "male",
    age: 34,
    email: "jackson.evans@x.dummyjson.com",
    role: "user",
  },
  {
    id: 21,
    firstName: "Madison",
    lastName: "Collins",
    gender: "female",
    age: 26,
    email: "madison.collins@x.dummyjson.com",
    role: "user",
  },
  {
    id: 22,
    firstName: "Elijah",
    lastName: "Stewart",
    gender: "male",
    age: 33,
    email: "elijah.stewart@x.dummyjson.com",
    role: "user",
  },
  {
    id: 23,
    firstName: "Chloe",
    lastName: "Morales",
    gender: "female",
    age: 39,
    email: "chloe.morales@x.dummyjson.com",
    role: "user",
  },
  {
    id: 24,
    firstName: "Mateo",
    lastName: "Nguyen",
    gender: "male",
    age: 30,
    email: "mateo.nguyen@x.dummyjson.com",
    role: "user",
  },
  {
    id: 25,
    firstName: "Harper",
    lastName: "Kelly",
    gender: "female",
    age: 27,
    email: "harper.kelly@x.dummyjson.com",
    role: "user",
  },
  {
    id: 26,
    firstName: "Evelyn",
    lastName: "Gonzalez",
    gender: "female",
    age: 35,
    email: "evelyn.gonzalez@x.dummyjson.com",
    role: "user",
  },
  {
    id: 27,
    firstName: "Daniel",
    lastName: "Cook",
    gender: "male",
    age: 41,
    email: "daniel.cook@x.dummyjson.com",
    role: "user",
  },
  {
    id: 28,
    firstName: "Lily",
    lastName: "Lee",
    gender: "female",
    age: 29,
    email: "lily.lee@x.dummyjson.com",
    role: "user",
  },
  {
    id: 29,
    firstName: "Henry",
    lastName: "Hill",
    gender: "male",
    age: 38,
    email: "henry.hill@x.dummyjson.com",
    role: "user",
  },
  {
    id: 30,
    firstName: "Addison",
    lastName: "Wright",
    gender: "female",
    age: 32,
    email: "addison.wright@x.dummyjson.com",
    role: "user",
  },
];
