export const vozaci = [
  {
    id: 177890,
    ime: "Anastasija",
    prezime: "Bojković",
    datumRodjenja: new Date(1997, 3, 20),
    automobil: undefined,
    brojPrijatelja: 99,
    mestoRodjenja: {
      zemlja: "Srbija",
      grad: "Zaječar",
    },
  },
  {
    id: 182341,
    ime: "Marko",
    prezime: "Jovanović",
    datumRodjenja: new Date(1995, 10, 5),
    automobil: "Audi A4",
    brojPrijatelja: 120,
    mestoRodjenja: {
      zemlja: "Srbija",
      grad: "Beograd",
    },
  },
  {
    id: 193552,
    ime: "Milica",
    prezime: "Petrović",
    datumRodjenja: new Date(1999, 6, 14),
    automobil: undefined,
    brojPrijatelja: 87,
    mestoRodjenja: {
      zemlja: "Srbija",
      grad: "Niš",
    },
  },
  {
    id: 165440,
    ime: "Nikola",
    prezime: "Živković",
    datumRodjenja: new Date(1993, 1, 9),
    automobil: "Volkswagen Golf 7",
    brojPrijatelja: 210,
    mestoRodjenja: {
      zemlja: "Srbija",
      grad: "Kragujevac",
    },
  },
  {
    id: 188743,
    ime: "Jelena",
    prezime: "Stevanović",
    datumRodjenja: new Date(2000, 8, 22),
    automobil: undefined,
    brojPrijatelja: 54,
    mestoRodjenja: {
      zemlja: "Srbija",
      grad: "Subotica",
    },
  },
  {
    id: 170225,
    ime: "Vladimir",
    prezime: "Milenković",
    datumRodjenja: new Date(1994, 11, 1),
    automobil: "Škoda Octavia",
    brojPrijatelja: 132,
    mestoRodjenja: {
      zemlja: "Srbija",
      grad: "Leskovac",
    },
  },
  {
    id: 199812,
    ime: "Sara",
    prezime: "Maksimović",
    datumRodjenja: new Date(1998, 4, 27),
    automobil: undefined,
    brojPrijatelja: 76,
    mestoRodjenja: {
      zemlja: "Srbija",
      grad: "Čačak",
    },
  },
  {
    id: 183907,
    ime: "Luka",
    prezime: "Radovanović",
    datumRodjenja: new Date(1996, 2, 13),
    automobil: "Peugeot 308",
    brojPrijatelja: 145,
    mestoRodjenja: {
      zemlja: "Srbija",
      grad: "Novi Sad",
    },
  },
  {
    id: 190334,
    ime: "Teodora",
    prezime: "Ilić",
    datumRodjenja: new Date(2001, 7, 30),
    automobil: undefined,
    brojPrijatelja: 67,
    mestoRodjenja: {
      zemlja: "Srbija",
      grad: "Vranje",
    },
  },
  {
    id: 172889,
    ime: "Stefan",
    prezime: "Stanković",
    datumRodjenja: new Date(1992, 0, 18),
    automobil: "Toyota Corolla",
    brojPrijatelja: 188,
    mestoRodjenja: {
      zemlja: "Srbija",
      grad: "Kraljevo",
    },
  },
];
